# Manifest file for clothing Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clothing-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clothing-dev
  template:
    metadata:
      labels:
        app: clothing-dev
    spec:
      containers:
      - name: clothing-dev
        image: DIT

---
apiVersion: v1
kind: Service
metadata:
  name: clothing-dev-svc
spec:
  selector:
    app: clothing-dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000